### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by Csonuzun** [Croupier-one/app#4]
1. Navigasyon çubuğunun site kaydırıldığında sabit kalması durumu değerlendirilsin duruma göre hangisi daha iyiyse tercih yapılsın
2. Navigasyon çubuğundaki yazıların hover rengi site temasına daha uyumlu hale getirilsin.

**Comment by yigitaydemir** [comment]
1. sticky nav icin tasarim uzerinde oynamak lazim
2. hover olunca renk degistirmek yerine border ekledim
